### PR TITLE
Update Sysmon_OSSEC-Decoders.xml

### PR DESCRIPTION
**Pull request by score1more4me**
This should work for both versions.  I simplified your originals to make them a little more flexible. HTH!

### CODE REVIEW

**Comment by defensivedepth** [comment]
I will look into it this week and merge if all appears well... I appreciate the input, as my Regex-Fu is not fantastic at this time...

**Comment by score1more4me** [comment]
My regex fu isn't great either... 

I did find a way to strip the SHA1= text from the Hashes on the V3 version if you're interested.

**Comment by defensivedepth** [comment]
@score1more4me I validated against Sysmon v1 & v3 EventID 1 logs, and all looks well except for the last capture group:

```
ParentImage: (\.*) \.*</regex>
```

It captures until it sees a space - some ParentImage paths contain spaces ie "C:\Program Files\etc" so the entire ParentImage is not captured, only up until the first space is encountered.

**Comment by defensivedepth** [comment]
And yes, I would be interested in stripping the SHA1/MD5/whatever text from hashes....

**Comment by score1more4me** [comment]
Hmm.  Do you want the decoder to be scoped to work on a default install of Sysmon (i.e. SHA1 hash = default).  It would be difficult to support all the hash types that sysmon supports.

I see the issues with the space in that Image Name.  Decoding in ossec is maddening work!  Basically, we want to snip everything between ParentImage: and ParentCommandLine:  but backslash.\* stops at spaces.  I'll take another swag at it tomorrow but I have some ideas :)

**Comment by defensivedepth** [comment]
Compatible with: 1.0, 2.0, 3.0 & 3.1

Thanks again!

**Pull request merged**
